### ISSUE TITLE
Help with setting up persistance

### ISSUE THREAD

**Issue by rsuhada** [joodland/bm#14]
I'm trying to make the bm bookmarks persistent across sessions (and load when the file is opened).
This is my setup based on my understanding now:

    (use-package bm
             :ensure t
             :diminish helm-mode
             :init
             (progn
               (setq bm-repository-size 100) ; nil means unlimitted
               (setq bm-marker 'bm-marker-left)
               (setq bm-highlight-style 'bm-highlight-only-fringe)
               (setq-default bm-buffer-persistence t)
               (setq-default bm-repository-file "~/.emacs.d/data/bm-bookmarks")
               (setq bm-restore-repository-on-load t)
               )
             :bind
             (("<M-S-f1>" . bm-toggle)
              ("<M-f1>" . bm-next)
              ("<S-f1>" . bm-previous))
             :config
             (progn (
                     (add-hook' after-init-hook 'bm-repository-load)
                     (add-hook 'find-file-hooks 'bm-buffer-restore)
                     (add-hook 'kill-buffer-hook 'bm-buffer-save)
                     (add-hook 'kill-emacs-hook '(lambda nil
                                                   (bm-buffer-save-all)
                                                   (bm-repository-save)))
                     )))

While I don't get errors (and the bookmarks work), the repository file is never created or loaded.
Any idea what am I doing incorrectly?

Thank you very much!

**Comment by joodland** [comment]
I have not used (use-package ...) before, but there seems to be some syntax errors when I evaluate your expression. You can evaluate the expression by moving the cursor after the last ")" and then press C-x C-e.

I get the expression to evaluate when:
* I remove the extra set of "()" inside the last (progn. 
* I fix the whitespace error (add-hook' after-init-hook ...).
* I fix the missing cons cells in the key binding. Add a "." between the elements in the list.

After evaluation both the key bindings and the hooks are set.

(use-package bm
         :ensure t
         :diminish helm-mode
         :init
         (progn
           (setq bm-repository-size 100) ; nil means unlimitted
           (setq bm-marker 'bm-marker-left)
           (setq bm-highlight-style 'bm-highlight-only-fringe)
           (setq-default bm-buffer-persistence t)
           (setq-default bm-repository-file "~/emacsd/data/bm-bookmarks")
           (setq bm-restore-repository-on-load t))
         :bind
         (("<M-S-f1>" . bm-toggle)
          ("<M-f1>" . bm-next)
          ("<S-f1>" . bm-previous))
         :config
         (progn 
           (add-hook 'after-init-hook 'bm-repository-load)
           (add-hook 'find-file-hooks 'bm-buffer-restore)
           (add-hook 'kill-buffer-hook 'bm-buffer-save)
           (add-hook 'kill-emacs-hook '(lambda nil
                                         (bm-buffer-save-all)
                                         (bm-repository-save)))
           ))

**Comment by rsuhada** [comment]
Ok, thank you - for me your snippet didn't work - the result was exactly the same as original (no error, everything working, except for persistance).

I removed the use-package, without it works.

Generally I really recommend use-package, it really helps to cleanup/speedup the config and except for bm I had no issues up to now!

**Comment by joodland** [comment]
When copy-pasting the code from your Github-issue, some dots disapeared. The bm-repository-file is incorrect in my code:
```
           (setq-default bm-repository-file "~/emacsd/data/bm-bookmarks")
```


The correct one should be the one from your snippet:

```
   (setq-default bm-repository-file "~/.emacs.d/data/bm-bookmarks")
```
