### ISSUE TITLE
"Experimental code for synchronizing with standard bookmarks" sound cool is there any documentation?

### ISSUE THREAD

**Issue by zeltak** [joodland/bm#20]
Hi

Just saw this today:

`Experimental code for synchronizing with standard bookmarks.`

is there any documentation on that? that sounds very cool :D

**Comment by joodland** [comment]
Hi,

It is not much documentation. There is the issue that started this #18 and the code itself, https://github.com/joodland/bm/blob/master/bm-sync.el
