### ISSUE TITLE
Please tag 20170815.1609 as a stable release

### ISSUE THREAD

**Issue by sten0** [joodland/bm#24]
Dear Jo,

Thank you for maintaining bm.el.  As 20170815.1609 has been in use for almost a year now, would you please consider tagging it as a stable release?

The Debian Emacsen Team is currently in the process of transitioning from emacs-goodies-el to a set of ELPA and MELPA packages.  As we have a policy of only using tagged releases it would be a shame to use `201610`, which only has 321 downloads rather than `20170815.1609` which is clearly the version most people want, as it has 11 531 downloads.

Thank you :-)
Nicholas

**Comment by joodland** [comment]
New release tag added, https://github.com/joodland/bm/releases/tag/201807

**Comment by sten0** [comment]
Thank you!
