### ISSUE TITLE
Feature request - add total bookmarks in buffer to the modeline

### ISSUE THREAD

**Issue by super-tomcat** [joodland/bm#31]
It would be handy if the total number of bookmarks in the current buffer could be included in the modeline, something simple like this is would do....

BM: 6

This allows a quick glance to see if there are actually any bookmarks in the buffer  (6 in this case) without having to open a new window with bm-show

This is a great package by the way, very useful, thanks for creating it

**Comment by joodland** [comment]
I have added support for adding the bookmark count to the mode line. You need to configure your mode line yourself, an example in the comments.

https://github.com/joodland/bm/commit/8bcda54bd37728389f8970bc3761e5dfa40dff1f

**Comment by super-tomcat** [comment]
![Untitled](https://user-images.githubusercontent.com/30247008/58438577-6bfb7680-80c7-11e9-8cba-3718434aada6.jpg)


Works a treat 👍 

Many thanks for adding this.

Cheers
Neil
