### ISSUE TITLE
Hi, could yo please add more explain or a video for how to use following keybinding?

### ISSUE THREAD

**Issue by zw963** [joodland/bm#43]
```
(global-set-key (kbd "<left-fringe> <mouse-5>") 'bm-next-mouse)
(global-set-key (kbd "<left-fringe> <mouse-4>") 'bm-previous-mouse)
(global-set-key (kbd "<left-fringe> <mouse-1>") 'bm-toggle-mouse)
```

**Comment by joodland** [comment]
[Fringes](https://www.gnu.org/software/emacs/manual/html_node/emacs/Fringes.html) are the small space on the left and right of the main window. The key bindings above are actions tied to clicking, with different mouse buttons, on the left fringe. I think it is only the last binding that makes sense, allowing you to toggle a bookmark on/off by clicking on the left fringe.

![CleanShot 2022-11-14 at 22 53 47](https://user-images.githubusercontent.com/595233/201776639-c979476e-ed9a-4348-88ca-a9cee027da2a.gif)
